### ISSUE TITLE
server酱貌似用不了了，请问能更新个推送方案吗师傅

### ISSUE THREAD

**Issue by Kar1chan** [dchaofei/watch-apple#1]
非常感谢！可惜不会go，不然就自己动手了

**Comment by dchaofei** [comment]
@Kar1chan 推荐个推送api呗，竟然除了我之外真的有人用这个程序😁

**Comment by Kar1chan** [comment]
> @Kar1chan 推荐个推送api呗，竟然除了我之外真的有人用这个程序😁

公众号： pushplus 推送加      
哈哈哈 师傅这个脚本正合我心意呀  正打算入手个ipad j结果就没了 我找了好几个 太花里胡哨了  还是这个小而美好用 就是server酱现在好像访问不到  所以只能寄托师傅帮忙修改一下了 试试上面那个 非常感谢！！

**Comment by Kar1chan** [comment]
> @Kar1chan 推荐个推送api呗，竟然除了我之外真的有人用这个程序😁

公众号： pushplus 推送加      
哈哈哈 师傅这个脚本正合我心意呀  正打算入手个ipad j结果就没了 我找了好几个 太花里胡哨了  还是这个小而美好用 就是server酱现在好像访问不到  所以只能寄托师傅帮忙修改一下了 试试上面那个 非常感谢！！

**Comment by dchaofei** [comment]
更新为 pushplus 了，请获取最新代码

不过你确定这个程序还有用吗？ 三年过去了， 如果有用回来反馈下哈

**Comment by Kar1chan** [comment]
谢谢师傅！ 一直在用呀 只是要时不时去看看  没法直接通知， 我现在去试试新版的
![image](https://user-images.githubusercontent.com/89959368/203898409-ac2d6938-c021-49a3-8097-7d4d15a66452.png)

**Comment by Kar1chan** [comment]
好像有点问题，不是成功才推送的吗师傅 就是每次的状态 他都会推送
![image](https://user-images.githubusercontent.com/89959368/203899948-c854989f-665d-45a8-aa14-5df6f4ed7ff3.png)

**Comment by dchaofei** [comment]
这是接口请求失败了

**Comment by dchaofei** [comment]
你看下 readme 里写的，不要替换 url， 只替换 后边的参数

**Comment by Kar1chan** [comment]
师傅，我试了还是不行，我wtachurl 替换了参数值
然后goodsurl 替换为商品链接  但是还是提示监控商品失败 方便留个vx吗

**Comment by Kar1chan** [comment]
x509: certificate signed by unknown authority

应该是证书的问题

**Comment by Kar1chan** [comment]
我换了台电脑就行了。。谢谢师傅 牛逼！ 坐等了

**Comment by dchaofei** [comment]
> 谢谢师傅！ 一直在用呀 只是要时不时去看看 没法直接通知， 我现在去试试新版的 ![image](https://user-images.githubusercontent.com/89959368/203898409-ac2d6938-c021-49a3-8097-7d4d15a66452.png)

我看了你监控的这个，银色的是有货，好像这个脚本默认只能监控一种颜色

**Comment by Kar1chan** [comment]
这个是之前的 我没使用推送接口去跑，我现在在用你更新过的去跑了，如果需要监控两个颜色我是不是得开两个终端跑啊，但是后面那个型号的参数值好像都一样，他监控应该不会只监控一个颜色把？

**Comment by dchaofei** [comment]
不同的颜色，参数值不一样，你监控几个就开几个终端写不同的配置吧，或者你可以学下go，改下脚本同时监控多个

**Comment by dchaofei** [comment]
我又改了下 readme，貌似还是这种看异步请求的url可靠，毕竟目前 apple 官网用的是这个接口
```
//打开浏览器控制台，然后刷新要买的 apple 翻新产品，应该能看到会发起一个 /shop/fulfillment-messages 异步请求，把完整链接复制到配置这里就行
"watchUrl": "https://www.apple.com.cn/shop/fulfillment-messages?little=false&parts.0=FU0Q2CH/A&mts.0=regular&fts=true",
```

**Comment by Kar1chan** [comment]
好的谢谢！
